name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the action on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[docs]'

      - name: Build Sphinx docs
        run: |
          sphinx-build -b html docs/ build/  # Replace `docs/` with the path to your Sphinx documentation source directory and `build/` with the desired output directory

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Replace with the same output directory used in the previous step
